In [1]:
import numpy as np


In [4]:
np.vstack([np.full((10, 2), -1), np.array([1,2]) ])

array([[-1, -1],
       [-1, -1],
       [-1, -1],
       [-1, -1],
       [-1, -1],
       [-1, -1],
       [-1, -1],
       [-1, -1],
       [-1, -1],
       [-1, -1],
       [ 1,  2]])

In [5]:
a = np.arange(12).reshape(3, 4)
print(a)
a[[[1, 2], [0, 1], [1, 1]], [[0], [1], [2]]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[4, 8],
       [1, 5],
       [6, 6]])

In [6]:
np.zeros((10, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [7]:
a = np.array([1,2,3])
b = np.array([1,4,3])
a @ b


18

In [8]:
a * b

array([1, 8, 9])

In [9]:
a = np.arange(12)
a[np.array([[0,1],[1,2],[2,1], [9,2]])]

array([[0, 1],
       [1, 2],
       [2, 1],
       [9, 2]])

In [18]:
np.arange(8).reshape((2,2,2))

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])