In [1]:
import numpy as np


In [2]:
a = np.arange(12).reshape((3, 4))


In [3]:
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
np.arange(3)[:, None]


array([[0],
       [1],
       [2]])

In [34]:
np.arange(len(a))[:, None]

array([[0],
       [1],
       [2]])

In [19]:
a[np.arange(len(a))[:, None], [[1, 2], [0, 1], [1, 3]]]


array([[ 1,  2],
       [ 4,  5],
       [ 9, 11]])

In [21]:
x = np.array([[[1], [2], [3]], [[4], [5], [6]]])
x


array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [33]:
np.arange(12).reshape(3, 4)[None, :, :].shape


(1, 3, 4)

In [30]:
a = np.arange(12).reshape(3, -1)
a
# a[:,:,np.newaxis]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a[None, :, :]


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [28]:
a[:, None, :]


array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [32]:
a[:, :, None]


array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])